services:
  backend:
    build: backend/
    restart: always
    ports:
      - 3000:3000
  frontend:
    build: frontend/
    restart: always
    environment:
      - VITE_BACKEND_URL=/api/
    depends_on:
      - backend
    volumes:
      - frontend-dist:/frontend-dist
    command: >
      sh -c "npm run build && 
      cp -R /usr/app/frontend/dist/* /frontend-dist/ && 
      tail -f /dev/null"
  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    volumes:
      - frontend-dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt

volumes: 
  frontend-dist: